#!/usr/bin/env python3
"""Print "<sha256>  <url>" for every file pinned in a pip --require-hashes lock file.

    tools/docker/wheel_manifest.py requirements/jetson-nano.lock > requirements/jetson-nano-wheels.txt

Run it whenever the lock changes. The file matching each pinned hash is looked up through PyPI's
JSON API; an entry with several hashes resolves to its universal (none-any) wheel. The Docker build
downloads the listed files with retries (tools/docker/fetch-wheels.sh) and installs them with
pip --no-index.
"""

import json
import re
import sys
import urllib.request

REQUIREMENT = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s\\]+)")
HASH = re.compile(r"--hash=sha256:([0-9a-f]{64})")


def parse_lock(path):
    entries = []
    with open(path, encoding="utf-8") as lock:
        for raw in lock:
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            match = REQUIREMENT.match(line)
            if match:
                entries.append({"name": match.group(1), "version": match.group(2), "hashes": []})
            if not entries:
                raise SystemExit("{0}: hash before any requirement: {1}".format(path, raw.strip()))
            entries[-1]["hashes"].extend(HASH.findall(line))
    return entries


def pypi_file(name, version, hashes):
    endpoint = "https://pypi.org/pypi/{0}/{1}/json".format(name, version)
    with urllib.request.urlopen(endpoint, timeout=60) as response:
        files = json.load(response)["urls"]
    matches = [item for item in files if item["digests"]["sha256"] in hashes]
    if len(matches) > 1:
        matches = [item for item in matches if item["filename"].endswith("-none-any.whl")]
    if len(matches) != 1:
        raise SystemExit("{0}=={1}: cannot choose one PyPI file for hashes {2}".format(
            name, version, ", ".join(hashes)))
    return matches[0]["digests"]["sha256"], matches[0]["url"]


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    lock_path = sys.argv[1]
    lines = ["# Generated by tools/docker/wheel_manifest.py from {0}; do not edit.".format(lock_path)]
    for entry in parse_lock(lock_path):
        if not entry["hashes"]:
            raise SystemExit("{0}: no --hash pinned".format(entry["name"]))
        lines.append("{0}  {1}".format(*pypi_file(entry["name"], entry["version"], entry["hashes"])))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
